/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mochilear.presentacion.view;

import java.awt.Color;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import mochilear.presentacion.control.ClientesControl;
import mochilear.presentacion.model.ClientesModel;

/**
 *
 * @author andres
 */
public class ClientesView extends javax.swing.JInternalFrame implements Observer {

    /**
     * Creates new form ClientesView
     */
    
    ClientesModel climod;
    ClientesControl clicon;

    public ClientesView() {
        initComponents();
        //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // para que no se cierre el programa
    }

    public void setClimod(ClientesModel climod) {
        this.climod = climod;
        this.climod.addObserver(this);
    }

    public void setClicon(ClientesControl clicon) {
        this.clicon = clicon;
    }

    public ClientesModel getClimod() {
        return climod;
    }

    public ClientesControl getClicon() {
        return clicon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_clientes = new javax.swing.JTable();
        criterio = new javax.swing.JLabel();
        buscar_txt = new javax.swing.JTextField();
        buscar_btn = new javax.swing.JButton();
        ver_todos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(225, 230, 226));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Consultas Clientes");

        tabla_clientes.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        tabla_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        this.tabla_clientes.getTableHeader().setBackground(new Color(13,42,56));
        this.tabla_clientes.getTableHeader().setForeground(new Color(254,254,254));
        tabla_clientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla_clientes.setCellSelectionEnabled(true);
        tabla_clientes.setShowHorizontalLines(false);
        tabla_clientes.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tabla_clientes);
        if (tabla_clientes.getColumnModel().getColumnCount() > 0) {
            tabla_clientes.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            tabla_clientes.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            tabla_clientes.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            tabla_clientes.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        criterio.setText("Criterio");

        buscar_btn.setBackground(new java.awt.Color(13, 46, 53));
        buscar_btn.setForeground(new java.awt.Color(254, 254, 254));
        buscar_btn.setText("Buscar");

        ver_todos.setBackground(new java.awt.Color(13, 42, 56));
        ver_todos.setForeground(new java.awt.Color(254, 254, 254));
        ver_todos.setText("Ver todos");
        ver_todos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ver_todosMouseClicked(evt);
            }
        });

        jLabel1.setText("Consultas Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(criterio)
                        .addGap(18, 18, 18)
                        .addComponent(buscar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buscar_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ver_todos)
                        .addGap(20, 20, 20))))
            .addGroup(layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel1)
                .addGap(0, 550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(criterio)
                    .addComponent(buscar_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar_btn)
                    .addComponent(ver_todos))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(180, 180, 180))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ver_todosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ver_todosMouseClicked
        clicon.desplegarTodosClientes();
    }//GEN-LAST:event_ver_todosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar_btn;
    private javax.swing.JTextField buscar_txt;
    private javax.swing.JLabel criterio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_clientes;
    private javax.swing.JButton ver_todos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.tabla_clientes.setModel(this.climod.getClitable());
    }
}
