/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumentospresentacion.View;

import instrumentospresentacion.Control.TipoInstrumentosControl;
import instrumentospresentacion.Model.TipoInstrumentosModel;
import instrumentospresentacion.Principal;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author marcovinicio
 */
public class TipoInstrumentosView extends javax.swing.JInternalFrame implements java.util.Observer{
    TipoInstrumentosControl controller;
    TipoInstrumentosModel model;

    //==========METODOS===================
    public TipoInstrumentosControl getController() {
        return controller;
    }
    //-------------------------------------
    public void setController(TipoInstrumentosControl controller) {
        this.controller = controller;
    }
    //-------------------------------------
    public TipoInstrumentosModel getModel() {
        return model;
    }
    //-------------------------------------
    public void setModel(TipoInstrumentosModel model) {
        this.model = model;
        model.addObserver(this);
    }
    
    /**
     * Creates new form tipoInstrumentosView
     */
    //-------------------------------------------------
    public TipoInstrumentosView() {
        initComponents();
    }
    //------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tipoInstTable = new javax.swing.JTable();
        nombreLb = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        buscarBt = new javax.swing.JButton();
        agregarBt = new javax.swing.JButton();
        borrarBt = new javax.swing.JButton();
        ExitBT = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tipoInstTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tipoInstTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoInstTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tipoInstTable);

        nombreLb.setText("Nombre");

        buscarBt.setText("Buscar");
        buscarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarBtActionPerformed(evt);
            }
        });

        agregarBt.setText("Agregar");
        agregarBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBtActionPerformed(evt);
            }
        });

        borrarBt.setText("Borrar");
        borrarBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarBtMouseClicked(evt);
            }
        });

        ExitBT.setText("Exit");
        ExitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarBt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreLb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(buscarBt))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(ExitBT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(borrarBt)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLb)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarBt))
                .addGap(18, 18, 18)
                .addComponent(agregarBt)
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrarBt)
                    .addComponent(ExitBT))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarBtActionPerformed
        controller.buscar();
    }//GEN-LAST:event_buscarBtActionPerformed

    private void agregarBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBtActionPerformed
        Principal.TIPOINST_VIEW.setLocation(this.agregarBt.getLocationOnScreen());
        controller.preAgregar();
    }//GEN-LAST:event_agregarBtActionPerformed

    private void tipoInstTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoInstTableMouseClicked
        if (evt.getClickCount() == 2) {
        int row = this.tipoInstTable.getSelectedRow();
        Principal.TIPOINST_VIEW.setLocation(evt.getLocationOnScreen());
        controller.editar(row);
      }
    }//GEN-LAST:event_tipoInstTableMouseClicked

    private void borrarBtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarBtMouseClicked
        int row = this.tipoInstTable.getSelectedRow();
        Principal.TIPOINST_VIEW.setLocation(evt.getLocationOnScreen());
        try {
            controller.borrar(row);
        } catch (Exception ex) {
            Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_borrarBtMouseClicked

    private void ExitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_ExitBTActionPerformed

    /**
     * @param args the command line arguments
     */
    //------------------------------------------------
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoInstrumentosView().setVisible(false);
            }
        });
    }
//---------------------------------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitBT;
    private javax.swing.JButton agregarBt;
    private javax.swing.JButton borrarBt;
    private javax.swing.JButton buscarBt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField nombreField;
    private javax.swing.JLabel nombreLb;
    private javax.swing.JTable tipoInstTable;
    // End of variables declaration//GEN-END:variables
//--------------------------------------------------
    
    @Override
    public void update(java.util.Observable updatedModel,Object parametros) {
     nombreField.setText(model.getFilter().getNombre());
       if (model.getErrores().get("nombreField")!=null){
            nombreLb.setBorder(Principal.BORDER_ERROR);
            nombreLb.setToolTipText(model.getErrores().get("nombreFld"));
        }
        else{
            nombreLb.setBorder(null);
            nombreLb.setToolTipText("");
        }
       
       tipoInstTable.setModel(model.getTinstrumentos());
       this.revalidate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }       
    }
}
