/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumentospresentacion.View;

import instrumentosEntidades.TipoInstrumento;
import instrumentospresentacion.Control.TipoInstrumentoControl;
import instrumentospresentacion.Model.TipoInstrumentoModel;
import instrumentospresentacion.Principal;
import java.util.Observable;
import javax.swing.JOptionPane;

/**
 *
 * @author marcovinicio
 */
public class TipoInstrumentoView extends javax.swing.JInternalFrame implements java.util.Observer {

    /**
     * Creates new form tipoInstrumentoView
     */
    public TipoInstrumentoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigoLb = new javax.swing.JLabel();
        codTextField = new javax.swing.JTextField();
        nombreLb = new javax.swing.JLabel();
        nomTextField = new javax.swing.JTextField();
        unidadLb = new javax.swing.JLabel();
        uniTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        codigoLb.setText("Codigo");

        nombreLb.setText("Nombre");

        unidadLb.setText("Unidad");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(codigoLb)
                                .addGap(26, 26, 26)
                                .addComponent(codTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLb, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(unidadLb))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomTextField)
                                    .addComponent(uniTextField)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoLb)
                    .addComponent(codTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLb)
                    .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadLb)
                    .addComponent(uniTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       this.control.guardar();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoInstrumentoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new TipoInstrumentoView().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelButton;
    public javax.swing.JTextField codTextField;
    private javax.swing.JLabel codigoLb;
    public javax.swing.JTextField nomTextField;
    private javax.swing.JLabel nombreLb;
    public javax.swing.JButton saveButton;
    public javax.swing.JTextField uniTextField;
    private javax.swing.JLabel unidadLb;
    // End of variables declaration//GEN-END:variables

    TipoInstrumentoModel model;
    TipoInstrumentoControl control;

    public TipoInstrumentoModel getModel() {
        return model;
    }

    public void setModel(TipoInstrumentoModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public TipoInstrumentoControl getControl() {
        return control;
    }

    public void setControl(TipoInstrumentoControl control) {
        this.control = control;
    }
    
    
    @Override
    public void update(java.util.Observable updatedModel,Object parametros) {
        TipoInstrumento TinstrumentoCurrent = model.getCurrent();
        
       this.codTextField.setEnabled(model.getModo()==Principal.MODO_AGREGAR);
       
       codTextField.setText(TinstrumentoCurrent.getCodigo());
       if (model.getErrores().get("codigo")!=null){
            codigoLb.setBorder(Principal.BORDER_ERROR);
            codigoLb.setToolTipText(model.getErrores().get("codigo"));
        }
        else{
            codigoLb.setBorder(null);
            codigoLb.setToolTipText("");
        }

        nomTextField.setText(TinstrumentoCurrent.getNombre());
        if (model.getErrores().get("nombre")!=null){
            nombreLb.setBorder(Principal.BORDER_ERROR);
            nombreLb.setToolTipText(model.getErrores().get("nombre"));
        }
        else{
           nombreLb.setBorder(null);
           nombreLb.setToolTipText("");
        }
        uniTextField.setText(TinstrumentoCurrent.getUnidad());
        if (model.getErrores().get("unidad")!=null){
            unidadLb.setBorder(Principal.BORDER_ERROR);
            unidadLb.setToolTipText(model.getErrores().get("unidad"));
        }
        else{
           unidadLb.setBorder(null);
           unidadLb.setToolTipText("");
        }
        
        //this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
